# CONSTANTS
DEF_RESOLUTION = (500,400)
DEF_EFFECT     = u"emboss"
DEF_FRAMERATE  = 15 

RED_ESCAPE     = u"\u001b[31m"
GREEN_ESCAPE   = u"\u001b[32m"
ESCAPE_END     = u"\u001b[0m"
WARNING_PREFIX = RED_ESCAPE + u"[!]" + ESCAPE_END
GOOD_PREFIX    = GREEN_ESCAPE + u"[*]" + ESCAPE_END
